name: Bookstore Backend workflow

on:
  push:
    paths:
      - "Order-Processing-Backend/**"
      - ".github/workflows/**"
    branches:
      - main

  pull_request:
    paths:
      - "Order-Processing-Backend/**"
      - ".github/workflows/**"
    types: [opened, synchronize, reopened]

  workflow_dispatch:

jobs:
  build:
    name: Build Spring-boot project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and generate test reports
        run: |
          cd Order-Processing-Backend/
          mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install

      - name: Add Codecov uploader
        run: |
          cd Order-Processing-Backend/
          curl -Os https://uploader.codecov.io/latest/linux/codecov 
          chmod +x codecov
          ./codecov


